apiVersion: v1
kind: Secret
metadata:
  name: cassandra-auth
  namespace: alnoor
type: Opaque
stringData:
  CASSANDRA_PASSWORD: ENC[AES256_GCM,data:REPLACE_ME,iv:REPLACE_ME,tag:REPLACE_ME,type:str]
sops:
  age:
    - recipient: age1replacewithyourteampublickeyxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        REPLACE_ME
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "1970-01-01T00:00:00Z"
  mac: ENC[AES256_GCM,data:REPLACE_ME,iv:REPLACE_ME,tag:REPLACE_ME,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.9.0
