apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fluxer-env
  namespace: alnoor
spec:
  encryptedData:
    FLUXER_CONFIG__DATABASE__CASSANDRA__PASSWORD: AgReplaceMe
    FLUXER_CONFIG__SERVICES__NATS__AUTH_TOKEN: AgReplaceMe
    FLUXER_CONFIG__S3__ACCESS_KEY_ID: AgReplaceMe
    FLUXER_CONFIG__S3__SECRET_ACCESS_KEY: AgReplaceMe
    FLUXER_CONFIG__AUTH__SUDO_MODE_SECRET: AgReplaceMe
    FLUXER_CONFIG__AUTH__CONNECTION_INITIATION_SECRET: AgReplaceMe
    FLUXER_CONFIG__AUTH__VAPID__PUBLIC_KEY: AgReplaceMe
    FLUXER_CONFIG__AUTH__VAPID__PRIVATE_KEY: AgReplaceMe
    FLUXER_CONFIG__SERVICES__ADMIN__SECRET_KEY_BASE: AgReplaceMe
    FLUXER_CONFIG__SERVICES__ADMIN__OAUTH_CLIENT_SECRET: AgReplaceMe
    FLUXER_CONFIG__SERVICES__MEDIA_PROXY__SECRET_KEY: AgReplaceMe
    FLUXER_CONFIG__SERVICES__GATEWAY__ADMIN_RELOAD_SECRET: AgReplaceMe
  template:
    metadata:
      name: fluxer-env
      namespace: alnoor
    type: Opaque
