apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cassandra-auth
  namespace: alnoor
spec:
  encryptedData:
    CASSANDRA_PASSWORD: AgReplaceMe
  template:
    metadata:
      name: cassandra-auth
      namespace: alnoor
    type: Opaque
