apiVersion: v1
kind: Service
metadata:
  name: cassandra
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: cassandra
  ports:
    - name: cql
      port: 9042
      targetPort: 9042
    - name: intra-node
      port: 7000
      targetPort: 7000
    - name: tls-intra
      port: 7001
      targetPort: 7001
