apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fluxer.fullname" . }}-env
  labels:
    {{- include "fluxer.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.envSecrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
