apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alnoor
resources:
  - default-deny-ingress.yaml
  - fluxer-egress-policy.yaml
  - valkey-ingress-policy.yaml
  - nats-ingress-policy.yaml
  - cassandra-ingress-policy.yaml
