apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fluxer-env
  namespace: alnoor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: fluxer-env
    creationPolicy: Owner
  data:
    - secretKey: FLUXER_CONFIG__DATABASE__CASSANDRA__PASSWORD
      remoteRef:
        key: alnoor/prod/database-cassandra-password
    - secretKey: FLUXER_CONFIG__SERVICES__NATS__AUTH_TOKEN
      remoteRef:
        key: alnoor/prod/nats-auth-token
    - secretKey: FLUXER_CONFIG__S3__ACCESS_KEY_ID
      remoteRef:
        key: alnoor/prod/s3-access-key-id
    - secretKey: FLUXER_CONFIG__S3__SECRET_ACCESS_KEY
      remoteRef:
        key: alnoor/prod/s3-secret-access-key
    - secretKey: FLUXER_CONFIG__AUTH__SUDO_MODE_SECRET
      remoteRef:
        key: alnoor/prod/auth-sudo-mode-secret
    - secretKey: FLUXER_CONFIG__AUTH__CONNECTION_INITIATION_SECRET
      remoteRef:
        key: alnoor/prod/auth-connection-initiation-secret
    - secretKey: FLUXER_CONFIG__AUTH__VAPID__PUBLIC_KEY
      remoteRef:
        key: alnoor/prod/auth-vapid-public-key
    - secretKey: FLUXER_CONFIG__AUTH__VAPID__PRIVATE_KEY
      remoteRef:
        key: alnoor/prod/auth-vapid-private-key
    - secretKey: FLUXER_CONFIG__SERVICES__ADMIN__SECRET_KEY_BASE
      remoteRef:
        key: alnoor/prod/admin-secret-key-base
    - secretKey: FLUXER_CONFIG__SERVICES__ADMIN__OAUTH_CLIENT_SECRET
      remoteRef:
        key: alnoor/prod/admin-oauth-client-secret
    - secretKey: FLUXER_CONFIG__SERVICES__MEDIA_PROXY__SECRET_KEY
      remoteRef:
        key: alnoor/prod/media-proxy-secret-key
    - secretKey: FLUXER_CONFIG__SERVICES__GATEWAY__ADMIN_RELOAD_SECRET
      remoteRef:
        key: alnoor/prod/gateway-admin-reload-secret
