apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alnoor
resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - service-valkey.yaml
  - statefulset-valkey.yaml
  - pdb-valkey.yaml
  - service-nats.yaml
  - statefulset-nats.yaml
  - pdb-nats.yaml
  - service-fluxer-server.yaml
  - deployment-fluxer-server.yaml
  - pdb-fluxer-server.yaml
  - hpa-fluxer-server.yaml
  - ingress-fluxer-server.yaml
  - networkpolicy-fluxer-ingress.yaml
