apiVersion: v1
kind: Secret
metadata:
  name: fluxer-env
type: Opaque
stringData:
  FLUXER_CONFIG__DATABASE__CASSANDRA__PASSWORD: replace-me
  FLUXER_CONFIG__SERVICES__NATS__AUTH_TOKEN: replace-me
  FLUXER_CONFIG__S3__ACCESS_KEY_ID: replace-me
  FLUXER_CONFIG__S3__SECRET_ACCESS_KEY: replace-me
  FLUXER_CONFIG__AUTH__SUDO_MODE_SECRET: replace-me
  FLUXER_CONFIG__AUTH__CONNECTION_INITIATION_SECRET: replace-me
  FLUXER_CONFIG__SERVICES__ADMIN__SECRET_KEY_BASE: replace-me
  FLUXER_CONFIG__SERVICES__ADMIN__OAUTH_CLIENT_SECRET: replace-me
  FLUXER_CONFIG__SERVICES__MEDIA_PROXY__SECRET_KEY: replace-me
  FLUXER_CONFIG__SERVICES__GATEWAY__ADMIN_RELOAD_SECRET: replace-me
  FLUXER_CONFIG__AUTH__VAPID__PUBLIC_KEY: replace-me
  FLUXER_CONFIG__AUTH__VAPID__PRIVATE_KEY: replace-me
